name: Build iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4 # Version 4 mise à jour

    - name: Set up Java
      uses: actions/setup-java@v4 # Version 4 mise à jour
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Pre-configure Project
      run: |
        flutter create . --platforms=ios
        flutter pub get

    - name: Build iOS
      run: flutter build ios --no-codesign

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4 # Version 4 mise à jour
      with:
        name: ios-build-output
        path: |
          build/ios/iphoneos/*.app
          build/ios/ipa/*.ipa
