name: Build iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Pre-configure Project
      run: |
        flutter create . --platforms=ios
        flutter pub get

    - name: Build IPA
      run: flutter build ios --no-codesign # Utilise la commande build ios native pour maximiser la compatibilité sans signature

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-build-output
        path: |
          build/ios/iphoneos/*.app
          build/ios/ipa/*.ipa
        if-no-files-found: error # Bloque l'action explicitement si le fichier est encore introuvable pour nous donner l'erreur exacte
