name: Build iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Fresh Flutter Project Generation
      run: |
        # 1. On crée un projet tout neuf à côté
        cd ..
        flutter create --project-name=cyber_app --platforms=ios fresh_project
        
        # 2. On remplace le main.dart par ton code stylé
        cp $GITHUB_WORKSPACE/lib/main.dart fresh_project/lib/main.dart
        
        # 3. On remet tout dans le dossier de build de GitHub
        rm -rf $GITHUB_WORKSPACE/*
        cp -r fresh_project/* $GITHUB_WORKSPACE/
        
        # 4. On récupère les dépendances
        cd $GITHUB_WORKSPACE
        flutter pub get

    - name: Build iOS
      run: |
        cd $GITHUB_WORKSPACE
        flutter build ios --no-codesign --verbose

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-output
        path: build/ios/iphoneos/Runner.app
